apiVersion: v1
kind: Service
metadata:
  name: nemoguardrails-server-service
  namespace: istio-system
spec:
  selector:
    app: nemoguardrails-server
  # Ports can be updated later
  ports:
    - port: 50053
      targetPort: 8000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nemoguardrails-server
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nemoguardrails-server
  template:
    metadata:
      labels:
        app: nemoguardrails-server
    spec:
      containers:
        - name: nemoguardrails-server
          # Built from Dockerfile https://github.com/NVIDIA-NeMo/Guardrails/blob/develop/Dockerfile
          # Build: docker build -t nemoguardrails:latest .
          # Load onto kind cluster: kind load docker-image nemoguardrails:latest --name mcp-gateway
          # Bot examples should be included in /config
          image: nemoguardrails:latest
          imagePullPolicy: IfNotPresent
          # Note: --server-url can only work for chat
          command: ["poetry", "run", "nemoguardrails"]
          args: ["server", "--verbose", "--config=/config"]
          # env:
          #   # This would be the directory within /config that would be the default to look in
          #   # If server complains about not being able to find config-ids
          #   - name: DEFAULT_CONFIG_ID
          #     value: "hello_world"
          ports:
            - containerPort: 8000

# Try port-forward oc port-forward svc/nemoguardrails-server-service 50053:50053 -n istio-system